### ISSUE TITLE
IndexError: index 1 is out of bounds for dimension 0 with size 1

### ISSUE THREAD

**Issue by 1zzc** [weihui1308/HotCold_Block#3]
val: New cache created: /home/zzc/zzc/stydy/HOTCOLDBlock-main/VOCFLIR/labels/val2017.cache
  0%|          | 0/277 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 159, in <module>
    swarm_parameters = pso.run()
  File "/home/zzc/zzc/stydy/HOTCOLDBlock-main/pso.py", line 125, in run
    fitness_candidate = self.fitness_function.evaluate(particle.position)
  File "/home/zzc/zzc/stydy/HOTCOLDBlock-main/pso.py", line 28, in evaluate
    patch_tf, patch_mask_tf = self.ptp(x, self.targets, self.imgs)
  File "/home/zzc/zzc/stydy/HOTCOLDBlock-main/ptop.py", line 50, in __call__
    patch_vertex_2_x = bbox_tl_x + x[1][1][0] * bbox_w
IndexError: index 1 is out of bounds for dimension 0 with size 1
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/zzc/anaconda3/envs/torch_gpu/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/zzc/anaconda3/envs/torch_gpu/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zzc/anaconda3/envs/torch_gpu/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 49, in _pin_memory_loop
    do_one_step()
  File "/home/zzc/anaconda3/envs/torch_gpu/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 26, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/zzc/anaconda3/envs/torch_gpu/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/home/zzc/anaconda3/envs/torch_gpu/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 305, in rebuild_storage_fd
    fd = df.detach()
  File "/home/zzc/anaconda3/envs/torch_gpu/lib/python3.8/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/zzc/anaconda3/envs/torch_gpu/lib/python3.8/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/zzc/anaconda3/envs/torch_gpu/lib/python3.8/multiprocessing/connection.py", line 508, in Client
    answer_challenge(c, authkey)
  File "/home/zzc/anaconda3/envs/torch_gpu/lib/python3.8/multiprocessing/connection.py", line 752, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/home/zzc/anaconda3/envs/torch_gpu/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/zzc/anaconda3/envs/torch_gpu/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/zzc/anaconda3/envs/torch_gpu/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

博主晚上好，加载FLIR数据集之后出现了IndexError: index 1 is out of bounds for dimension 0 with size 1情况，这个是啥问题呀

感谢博主的回复❀

**Comment by 1zzc** [comment]
ptop.py是否最新版本 

ptop.py的第50行左右代码为：
            print(x,'x')
            # second point
            patch_vertex_2_x = bbox_tl_x + x[1][1][0] * bbox_w
            patch_vertex_2_y = bbox_tl_y + x[1][1][1] * bbox_h

list类型的x的打印结果为：
[tensor([[0., 0., 1.],
        [1., 0., 1.],
        [1., 1., 1.]], device='cuda:0'), tensor([[0.48111, 0.09980]], device='cuda:0')] 

感谢博主的帮助❀

**Comment by 1zzc** [comment]
我需要博主的微信或者邮箱，想向大佬学习。
我的微信号：18272443583，十分感谢大佬的帮助Thanks♪(･ω･)ﾉ

**Comment by weihui1308** [comment]
pso.py--->110行
self.swarm.append(Particle(dimensions=1, device=device))

其中的参数dimensions需要根据你当前使用的patch数量进行调整。如果使用的是4块，应将dimensions设置为4。
