### ISSUE TITLE
Request for Documentation in HOTCOLDBlock

### ISSUE THREAD

**Issue by Louquinze** [weihui1308/HotCold_Block#8]
Hi there,

I recently came across your HOTCOLDBlock repository and I'm really impressed with what I see! I'd like to use this repo for a project that I'm plan to work on with the University of Tokyo, but I noticed that there's a lack of documentation.

As a researcher at the National Institute of Informatics (NII), having documentation would be extremely helpful to us in our collaborative project with the University of Tokyo. I was wondering if it would be possible to add some documentation to the repo to help users like myself get started with using it? Alternatively, if there are any existing resources or guides that you could point me to, that would be really helpful too.

I understand that maintaining open source projects can be a lot of work, so please don't feel pressured to add documentation if it's not feasible. However, if you are open to collaborating on this, we would be happy to help in any way that we can.

Thank you for your time and consideration!

Best regards,

Lukas Strack

**Comment by weihui1308** [comment]
Thank you for your interest in our work. 
I don't understand what you are referring to when you say documentation.

**Comment by wangxueping78** [comment]
> Thank you for your interest in our work. I don't understand what you are referring to when you say documentation.

I am doing research related to physical infrared adversarial attack and I would like make a comparison experiment with your method. Could you please tell me how long does it take you to implement such a physical attack in the real world?

**Comment by Louquinze** [comment]
> Thank you for your interest in our work. I don't understand what you are referring to when you say documentation.

Thank you for this fast answer. With documentation I mean a document or any kind of information, which explains how the repo works beside from how to install the dependencies. For example where to store the dataset I want to use it and in which format labels etc. are supposed to be stored.

Thank you for your support

best wishes

Lukas Strack

**Comment by weihui1308** [comment]
OK，I see.

I will add it to the readme file as soon as possible (I think it should take 3 days).

**Comment by Louquinze** [comment]
Thank you :)

**Comment by Louquinze** [comment]
Hey thank you for you additional informations. For me the Repo is still not working as intend.

1. PatchApplier_v1 is not defined
2. ParticleToPatch_One is not defined
3. ParticleToPatch_Four is not defined

This are the main errors I get. Also there are minor issues with the path e.g. there is not `utils` but only `victim_detector.utils` also libaries like kornia, pandas, matplotlib and seaborn do not appear in the `requirements.txt`.

I made a list to trace some of the error I encountered:

```
ERROR: Could not find a version that satisfies the requirement torch==1.10.1+cu111 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==1.10.1+cu111

 python main.py --epochs 5
Traceback (most recent call last):
  File "/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/main.py", line 50, in <module>
    import val_patch
  File "/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/val_patch.py", line 29, in <module>
    from utils_patch import PatchApplier_v1
ImportError: cannot import name 'PatchApplier_v1' from 'utils_patch' (/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/utils_patch.py)


python main.py --epochs 5
Traceback (most recent call last):
  File "/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/main.py", line 50, in <module>
    import val_patch
  File "/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/val_patch.py", line 30, in <module>
    from ptop import ParticleToPatch_Four
ImportError: cannot import name 'ParticleToPatch_Four' from 'ptop' (/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/ptop.py)


python main.py --epochs 5
Traceback (most recent call last):
  File "/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/main.py", line 51, in <module>
    from pso import OptimizeFunction, PSO
  File "/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/pso.py", line 8, in <module>
    from ptop import ParticleToPatch_One
ImportError: cannot import name 'ParticleToPatch_One' from 'ptop' (/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/ptop.py)


Traceback (most recent call last):
  File "/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/main.py", line 93, in <module>
    ckpt = torch.load(weights, map_location='cpu')
  File "/home/lukas/anaconda3/envs/HotCold/lib/python3.9/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/lukas/anaconda3/envs/HotCold/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/lukas/anaconda3/envs/HotCold/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'runs/train/exp/weights/best.pt'


Traceback (most recent call last):
  File "/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/main.py", line 111, in <module>
    train_loader, dataset = create_dataloader(train_path,
  File "/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/victim_detector/utils/datasets.py", line 116, in create_dataloader
    dataset = LoadImagesAndLabels(
  File "/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/victim_detector/utils/datasets.py", line 477, in __init__
    bi = np.floor(np.arange(n) / batch_size).astype(np.int)  # batch index
  File "/home/lukas/anaconda3/envs/HotCold/lib/python3.9/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations


train: Scanning '/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/datasets/FLIR/labels/train.cache' images and labels... 1169 found, 0 missing, 0 e
val: Scanning '/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/datasets/FLIR/labels/val.cache' images and labels... 86 found, 0 missing, 0 empty,
  0%|          | 0/37 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/main.py", line 160, in <module>
    swarm_parameters = pso.run()
  File "/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/pso.py", line 125, in run
    fitness_candidate = self.fitness_function.evaluate(particle.position)
  File "/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/pso.py", line 28, in evaluate
    patch_tf, patch_mask_tf = self.ptp(x, self.targets, self.imgs)
  File "/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/ptop.py", line 50, in __call__
    patch_vertex_2_x = bbox_tl_x + x[1][1][0] * bbox_w
IndexError: index 1 is out of bounds for dimension 0 with size 1
```

The last error I have no idea how to fix, because this is no issue with like wrong path. I would be glad if you could maybe check this again.

best wishes

Lukas

**Comment by weihui1308** [comment]
Sorry for the bugs.

I re-debugged the code. Please re-download it.

If there are any more bugs, please let me know. Thanks.

**Comment by Louquinze** [comment]
Hello,

Firstly, I want to extend my gratitude for your prompt responses and the efforts you have put into debugging and updating the code. I really appreciate your hard work.

Despite your recent updates, I'm still encountering some major issues that prevent me from using the repository effectively. Here are a few notable issues I have come across:

1. Directory name 'victim detector': In Python, directory names should not contain spaces if they are intended to be used as a package. Could you consider renaming it to 'victim_detector' so that it can be imported as a module? This change would greatly help with the usability of your repository.

2. Import and usage inconsistencies in 'pso.py': On line 7, the 'PatchApplier' is imported, but on line 16, 'PatchApplier_v1()' is being used. I believe this might be an oversight. Could you please clarify if it should be 'PatchApplier' or 'PatchApplier_v1'?

I understand that maintaining and debugging code can be a complex and time-consuming process, especially for an open-source project. So, I appreciate your patience in addressing these issues. Could you please verify if the version that's currently uploaded and available has been tested and is expected to work without these issues? 

Thank you again for your assistance and I look forward to your response.

Best regards,
Lukas Strack

**Comment by weihui1308** [comment]
Hello!
Sorry for the bugs.
1. I renamed the 'victim detector' to 'victim_detector'.
2. In 'pso.py', self.pa = PatchApplier_v1() --> self.pa = PatchApplier()

**Comment by Louquinze** [comment]
Hey thank you for the quick fix :) Unfortunately, there are still errors here are a bigger list with issues i ran into and how i fixed some of them to the point where i got stuck

# Errors during running library

## Init library
```
(HotCold) lukas@lukas-Blade-15-Base-Model-Early-2020-RZ09-0328:~/PycharmProjects/HotCold$ git clone https://github.com/weihui1308/HOTCOLDBlock
Klone nach 'HOTCOLDBlock' …
remote: Enumerating objects: 121, done.
remote: Counting objects: 100% (121/121), done.
remote: Compressing objects: 100% (114/114), done.
remote: Total 121 (delta 42), reused 0 (delta 0), pack-reused 0
Empfange Objekte: 100% (121/121), 412.89 KiB | 907.00 KiB/s, fertig.
Löse Unterschiede auf: 100% (42/42), fertig.
(HotCold) lukas@lukas-Blade-15-Base-Model-Early-2020-RZ09-0328:~/PycharmProjects/HotCold$ cd HOTCOLDBlock-main
bash: cd: HOTCOLDBlock-main: File or directory not found
```

### Fix
the directory is actually named **HOTCOLDBlock** and not **HOTCOLDBlock-main**

## Requirements error
 **mpi4py** is not installable:
```
pip install mpi4py
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mpi4py
Failed to build mpi4py
ERROR: Could not build wheels for mpi4py, which is required to install pyproject.toml-based projects
```

## main.py error

### define model
```
 python main.py --epochs 5
main: cfg=victim_detector/models/yolov5s.yaml, batch_size=32, device=, profile=False, line_profile=False, test=False, data=victim_detector/data/custom.yaml, imgsz=640, single_cls=False, quad=False, cache=None, rect=False, local_rank=-1, image_weights=False, workers=8, noval=False, epochs=5, label_smoothing=0.0, patch_size=0.14
main: cfg=victim_detector/models/yolov5s.yaml, batch_size=32, device=, profile=False, line_profile=False, test=False, data=victim_detector/data/custom.yaml, imgsz=640, single_cls=False, quad=False, cache=None, rect=False, local_rank=-1, image_weights=False, workers=8, noval=False, epochs=5, label_smoothing=0.0, patch_size=0.14
YOLOv5 🚀 2023-5-31 torch 1.10.1+cu102 CUDA:0 (NVIDIA GeForce RTX 2060, 5935MiB)

YOLOv5 🚀 2023-5-31 torch 1.10.1+cu102 CUDA:0 (NVIDIA GeForce RTX 2060, 5935MiB)

Traceback (most recent call last):
  File "/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/main.py", line 92, in <module>
    ckpt = torch.load(weights, map_location='cpu')
  File "/home/lukas/anaconda3/envs/HotCold/lib/python3.9/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/lukas/anaconda3/envs/HotCold/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/lukas/anaconda3/envs/HotCold/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'xxx/best.pt'

```

in main.py weights are hard coded to invalid weight
```python
# Create model
    hyp = 'victim_detector/data/hyps/hyp.scratch-low.yaml'
    if isinstance(hyp, str):
        with open(hyp, errors='ignore') as f:
            hyp = yaml.safe_load(f)
    
    weights = "xxx/best.pt"
    ckpt = torch.load(weights, map_location='cpu')
    model = Model(ckpt['model'].yaml, ch=3, nc=80, anchors=hyp.get('anchors')).to(device)
    exclude = ['anchor'] if (hyp.get('anchors')) and not resume else []
    csd = ckpt['model'].float().state_dict()
    csd = intersect_dicts(csd, model.state_dict(), exclude=exclude)
    model.load_state_dict(csd, strict=False)
```


### define dataset
In custom.yaml the path is not correctly defined has to be done by hand

```
path: path/dataset/FLIR
train: images/train
val: images/val

# Classes
nc: 1  # number of classes
names: ['pedestrian']  # class names
```

## After fixing initialization issues
`python main.py --epochs 5`

```
[34m[1mmain: [0mcfg=victim_detector/models/yolov5s.yaml, batch_size=32, device=, profile=False, line_profile=False, test=False, data=victim_detector/data/custom.yaml, imgsz=640, single_cls=False, quad=False, cache=None, rect=False, local_rank=-1, image_weights=False, workers=8, noval=False, epochs=5, label_smoothing=0.0, patch_size=0.14
[34m[1mmain: [0mcfg=victim_detector/models/yolov5s.yaml, batch_size=32, device=, profile=False, line_profile=False, test=False, data=victim_detector/data/custom.yaml, imgsz=640, single_cls=False, quad=False, cache=None, rect=False, local_rank=-1, image_weights=False, workers=8, noval=False, epochs=5, label_smoothing=0.0, patch_size=0.14
YOLOv5 🚀 2023-5-31 torch 1.10.1+cu102 CUDA:0 (NVIDIA GeForce RTX 2060, 5935MiB)

YOLOv5 🚀 2023-5-31 torch 1.10.1+cu102 CUDA:0 (NVIDIA GeForce RTX 2060, 5935MiB)


                 from  n    params  module                                  arguments                     

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]              
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]              
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  2    115712  models.common.C3                        [128, 128, 2]                 
  4                -1  2    115712  models.common.C3                        [128, 128, 2]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  3    625152  models.common.C3                        [256, 256, 3]                 
  6                -1  3    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1   1182720  models.common.C3                        [512, 512, 1]                 
  8                -1  1   1182720  models.common.C3                        [512, 512, 1]                 
  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]                 
  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]                 
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1    229245  victim_detector.models.yolo.Detect      [80, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
 24      [17, 20, 23]  1    229245  victim_detector.models.yolo.Detect      [80, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model summary: 270 layers, 7235389 parameters, 7235389 gradients, 16.5 GFLOPs
Model summary: 270 layers, 7235389 parameters, 7235389 gradients, 16.5 GFLOPs


{'path': '/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/dataset/FLIR', 'train': '/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/dataset/FLIR/images/train', 'val': '/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/dataset/FLIR/images/val', 'nc': 1, 'names': ['pedestrian']}

[34m[1mtrain: [0mScanning '/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/dataset/FLIR/labels/train.cache' images and labels... 1169 found, 0 missing, 0 empty, 0 corrupt: 100%|██████████| 1169/1169 [00:00<?, ?it/s]
[34m[1mtrain: [0mScanning '/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/dataset/FLIR/labels/train.cache' images and labels... 1169 found, 0 missing, 0 empty, 0 corrupt: 100%|██████████| 1169/1169 [00:00<?, ?it/s]

[34m[1mval: [0mScanning '/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/dataset/FLIR/labels/val.cache' images and labels... 86 found, 0 missing, 0 empty, 0 corrupt: 100%|██████████| 86/86 [00:00<?, ?it/s]
[34m[1mval: [0mScanning '/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/dataset/FLIR/labels/val.cache' images and labels... 86 found, 0 missing, 0 empty, 0 corrupt: 100%|██████████| 86/86 [00:00<?, ?it/s]

  0%|          | 0/37 [00:00<?, ?it/s]
  0%|          | 0/37 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/main.py", line 159, in <module>
    swarm_parameters = pso.run()
  File "/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/pso.py", line 125, in run
    fitness_candidate = self.fitness_function.evaluate(particle.position)
  File "/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/pso.py", line 28, in evaluate
    patch_tf, patch_mask_tf = self.ptp(x, self.targets, self.imgs)
  File "/home/lukas/PycharmProjects/HotCold/HOTCOLDBlock/ptop.py", line 50, in __call__
    patch_vertex_2_x = bbox_tl_x + x[1][1][0] * bbox_w
IndexError: index 1 is out of bounds for dimension 0 with size 1
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/lukas/anaconda3/envs/HotCold/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/lukas/anaconda3/envs/HotCold/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lukas/anaconda3/envs/HotCold/lib/python3.9/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/lukas/anaconda3/envs/HotCold/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/lukas/anaconda3/envs/HotCold/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/home/lukas/anaconda3/envs/HotCold/lib/python3.9/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/lukas/anaconda3/envs/HotCold/lib/python3.9/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/lukas/anaconda3/envs/HotCold/lib/python3.9/multiprocessing/reduction.py", line 157, in recvfds
    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_SPACE(bytes_size))
ConnectionResetError: [Errno 104] Connection reset by peer
```

I get dimension issues in `ptop.py`

```
HotCold/HOTCOLDBlock/ptop.py", line 50, in __call__
    patch_vertex_2_x = bbox_tl_x + x[1][1][0] * bbox_w
IndexError: index 1 is out of bounds for dimension 0 with size 1
```

**Comment by weihui1308** [comment]
I found the problem.

Need to modify line 110 in pso.py file: dimensions=1 --> dimensions=4.

This parameter needs to be consistent with the number of patches.

**Comment by Louquinze** [comment]
thank you for your help :)
